# Config file for automatic testing at travis-ci.org
sudo: false
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements/dev.txt
script: flask test
